package local.poc.blockchain.customers.management.registration.persistence.repository;

public class CorporationOfficialDocumentRepositoryImpl
implements CorporationOfficialDocumentRepositoryCustom {

}